import * as T from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { RoomEnvironment } from "three/addons/environments/RoomEnvironment.js";
import { buildObject, type Assembly } from "./objects";
import type { ProductId } from "./products";
type State={separation:number;selected:number|null;autoRotate:boolean;onPick:(i:number)=>void;onExplode:()=>void};
export class ObjectEngine {
 private renderer:T.WebGLRenderer;private scene=new T.Scene();private camera=new T.OrthographicCamera();private controls:OrbitControls;private assembly:Assembly;private observer:ResizeObserver;private frame=0;private environment:T.WebGLRenderTarget;private width=1;private height=1;private progress=0;private lastTime=0;private reduced=window.matchMedia("(prefers-reduced-motion: reduce)");private start={x:0,y:0,multi:false};private pointers=new Set<number>();private disposed=false;private activeSelection:number|null=null;
 constructor(private host:HTMLElement,private id:ProductId,private getState:()=>State,private pins:(HTMLButtonElement|null)[],private onError:()=>void){
  this.renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));this.renderer.setClearColor(0x000000,0);this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.outputColorSpace=T.SRGBColorSpace;
  const canvas=this.renderer.domElement;canvas.tabIndex=0;canvas.setAttribute("aria-label",`${id==="oura"?"Oura Ring 4":"iPhone 16 Pro"} 3D model. Press Enter to unfold, arrow keys to rotate, plus or minus to zoom.`);canvas.setAttribute("role","img");host.prepend(canvas);
  const generator=new T.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.environment=generator.fromScene(room,.05);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=1.5;room.dispose();generator.dispose();
  this.scene.add(new T.HemisphereLight(0xffffff,0x969d98,2));const key=new T.DirectionalLight(0xffffff,3.3);key.position.set(3,8,5);this.scene.add(key);const rim=new T.DirectionalLight(0xc4d9ef,1.7);rim.position.set(-5,2,-3);this.scene.add(rim);
  this.assembly=buildObject(id);this.scene.add(this.assembly.group);
  this.camera.near=.1;this.camera.far=100;this.positionCamera();this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.075;this.controls.enablePan=false;this.controls.minZoom=.65;this.controls.maxZoom=2.8;this.controls.rotateSpeed=.65;this.controls.zoomSpeed=.65;this.controls.autoRotateSpeed=.55;this.controls.target.set(0,0,0);this.controls.update();
  canvas.addEventListener("pointerdown",this.down);canvas.addEventListener("pointerup",this.up);canvas.addEventListener("pointercancel",this.cancel);canvas.addEventListener("keydown",this.key);canvas.addEventListener("webglcontextlost",this.contextLost);
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.resize();this.frame=requestAnimationFrame(this.draw);
 }
 private positionCamera(){this.camera.position.set(...(this.id==="oura"?[5.4,6.8,9]:[7,4,-11]) as [number,number,number]);this.camera.lookAt(0,0,0);}
 private resize(){this.width=Math.max(this.host.clientWidth,1);this.height=Math.max(this.host.clientHeight,1);this.renderer.setSize(this.width,this.height);this.projection();}
 private projection(){const aspect=this.width/this.height;const initial=this.id==="oura"?4.0:7.4,expanded=this.id==="oura"?7.8:10.8;const size=(initial+(expanded-initial)*this.progress)*Math.max(1,.94/aspect);this.camera.left=-size*aspect/2;this.camera.right=size*aspect/2;this.camera.top=size/2;this.camera.bottom=-size/2;this.camera.updateProjectionMatrix();}
 reset(){this.controls.reset();this.positionCamera();this.camera.zoom=1;this.controls.target.set(0,0,0);this.controls.update();this.projection();}
 zoom(f:number){this.camera.zoom=T.MathUtils.clamp(this.camera.zoom/f,.65,2.8);this.camera.updateProjectionMatrix();}
 private down=(e:PointerEvent)=>{this.pointers.add(e.pointerId);if(this.pointers.size>1)this.start.multi=true;else this.start={x:e.clientX,y:e.clientY,multi:false};};
 private cancel=(e:PointerEvent)=>{this.pointers.delete(e.pointerId);this.start.multi=true;};
 private up=(e:PointerEvent)=>{this.pointers.delete(e.pointerId);if(this.start.multi||Math.hypot(e.clientX-this.start.x,e.clientY-this.start.y)>7)return;const box=this.renderer.domElement.getBoundingClientRect(),point=new T.Vector2((e.clientX-box.left)/box.width*2-1,-(e.clientY-box.top)/box.height*2+1),ray=new T.Raycaster();ray.setFromCamera(point,this.camera);const hits=ray.intersectObject(this.assembly.group,true);if(hits.length){const s=this.getState();if(s.separation<10)s.onExplode();else if(typeof hits[0].object.userData.part==="number")s.onPick(hits[0].object.userData.part);}};
 private key=(e:KeyboardEvent)=>{const s=new T.Spherical().setFromVector3(this.camera.position.clone().sub(this.controls.target));if(e.key==="ArrowLeft")s.theta-=.14;else if(e.key==="ArrowRight")s.theta+=.14;else if(e.key==="ArrowUp")s.phi=Math.max(.15,s.phi-.14);else if(e.key==="ArrowDown")s.phi=Math.min(Math.PI-.15,s.phi+.14);else if(e.key==="Enter"||e.key===" "){this.getState().onExplode();e.preventDefault();return;}else if(e.key==="+"||e.key==="="){this.zoom(.85);e.preventDefault();return;}else if(e.key==="-"){this.zoom(1.18);e.preventDefault();return;}else return;e.preventDefault();this.camera.position.setFromSpherical(s).add(this.controls.target);this.controls.update();};
 private contextLost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(this.frame);this.onError();};
 private draw=(now:number)=>{
  if(this.disposed)return;const dt=Math.min((now-this.lastTime)/1000,.05);this.lastTime=now;const state=this.getState(),target=state.separation/100;this.progress=this.reduced.matches?target:T.MathUtils.damp(this.progress,target,5.5,dt);if(Math.abs(this.progress-target)<.0001)this.progress=target;
  this.assembly.parts.forEach(p=>p.object.position.copy(p.base).addScaledVector(p.offset,this.progress));
  this.assembly.smallPieces.forEach(o=>{if(o.userData.microBase)o.position.copy(o.userData.microBase).addScaledVector(o.userData.microOffset,this.progress);});
  if(state.selected!==this.activeSelection){this.activeSelection=state.selected;this.assembly.group.traverse(o=>{if(o instanceof T.Mesh){const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{if(m instanceof T.MeshStandardMaterial){if(m.userData.originalEmissive===undefined){m.userData.originalEmissive=m.emissive.clone();m.userData.originalIntensity=m.emissiveIntensity;}m.emissive.copy(m.userData.originalEmissive);m.emissiveIntensity=m.userData.originalIntensity;}});}});
   // Clone selected materials so identical metals in other groups keep their finish.
   this.assembly.parts.forEach((p,i)=>p.object.traverse(o=>{if(o instanceof T.Mesh&&!Array.isArray(o.material)&&o.material instanceof T.MeshStandardMaterial){if(!o.userData.ownMaterial){o.material=o.material.clone();o.userData.ownMaterial=true;}const m=o.material as T.MeshStandardMaterial;if(i===state.selected){m.emissive.set("#d45d28");m.emissiveIntensity=.2;}}}));
  }
  this.controls.autoRotate=state.autoRotate&&!this.reduced.matches;this.controls.update(dt);this.projection();this.scene.updateMatrixWorld(true);
  this.assembly.parts.forEach((p,i)=>{const pin=this.pins[i];if(!pin)return;const anchor=p.object.localToWorld(p.anchor.clone()).project(this.camera);const visible=this.progress>.15&&anchor.z>-1&&anchor.z<1&&Math.abs(anchor.x)<.96&&Math.abs(anchor.y)<.93;pin.style.display=visible?"block":"none";if(visible){pin.style.left=`${(anchor.x*.5+.5)*this.width}px`;pin.style.top=`${(-anchor.y*.5+.5)*this.height}px`;pin.style.opacity=String(Math.min(1,(this.progress-.15)*4));}});
  this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(this.draw);
 };
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.observer.disconnect();this.controls.dispose();const canvas=this.renderer.domElement;canvas.removeEventListener("pointerdown",this.down);canvas.removeEventListener("pointerup",this.up);canvas.removeEventListener("pointercancel",this.cancel);canvas.removeEventListener("keydown",this.key);canvas.removeEventListener("webglcontextlost",this.contextLost);const materials=new Set<T.Material>(),textures=new Set<T.Texture>();this.scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});materials.forEach(m=>{for(const v of Object.values(m))if(v instanceof T.Texture)textures.add(v);m.dispose();});textures.forEach(t=>t.dispose());this.environment.dispose();this.renderer.dispose();canvas.remove();}
}
